name: pyracer-srv deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2

    - name: Create Virtual Environment
      run: |
        python3 -m venv .venv 
        . .venv/bin/activate 

    - name: Install dependencies
      run: |
        . .venv/bin/activate
        python -m pip install poetry
        poetry export --without-hashes --with dev --format=requirements.txt > requirements.txt
        python -m pip install -r requirements.txt
    
    - name: Run Lint
      run: |
        . .venv/bin/activate  
        python -m ruff check .

    - name: Run Test
      run: |
        . .venv/bin/activate
        python -m pytest -vv
      
