name: pyracer-srv deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2

    - name: Create Virtual Environment
      run: python3 -m venv .venv && source .venv/bin/activate

    - name: Install dependencies
      run: make install

    - name: Run Lint
      run: make lint

    - name: Run Test
      run: make test
